site_name: Runbooks
site_url: https://runbooks.com.au/

repo_url: https://github.com/ash-kavousi/runbooks
edit_uri: edit/master/MkDocs/docs/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    # - toc.integrate --> removed because of simplicity
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.meta
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Networking:
      - IPv4 Fundamentals: networking/ipv4.md
  - Security:
      - Understanding Cyber Risk: security/understanding_risk_assessment.md
      - Risk Assessment Process: security/risk_assessment_steps_v2.md
      - Risk Assessment Methods: security/qualitative_vs_quantitative_risk_assessment_v1.md
  - Operations:
      - Overview: operations/index.md
  - Tags: tags.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid


extra_css:
  - stylesheets/layout-overrides.css

plugins:
  - search
  - tags:
     tags_file: tags.md
  - mermaid2:
      javascript: https://unpkg.com/mermaid@10/dist/mermaid.min.js


copyright: >
  Â© 2026 Runbooks. Content is provided for educational purposes only.
  No warranty is expressed or implied.


